In [5]:
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# Define a custom dataset for PyTorch
class CustomDataset(Dataset):
    def __init__(self, data, targets, transform=None):
        self.data = data
        self.targets = targets
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        x = self.data[index]
        y = self.targets[index]

        if self.transform is not None:
            x = self.transform(x)

        return x, y

# Convert numpy arrays to PyTorch tensors
# data = np.random.randn(100, 2).astype(np.float32)  # 100 rows, 2 columns
# targets = np.random.randint(0, 2, size=(100,)).astype(np.float32)  # 100 binary target labels (0 or 1)
data = torch.from_numpy(np.random.randn(100, 2).astype(np.float32))  # 100 rows, 2 columns
targets = torch.from_numpy(np.random.randint(0, 2, size=(100,)).astype(np.float32))  # 100 binary target labels (0 or 1)

# Create the PyTorch dataset
# transform = transforms.Compose([transforms.ToTensor()])
dataset = CustomDataset(data, targets)

# Create the data loader
batch_size = 32
data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Iterate over the dataset and print the elements
for x, y in data_loader:
    print(f"x: {x}, {type(x)}, y: {y}, {type(y)}")

# Define the model architecture
class BinaryClassificationModel(nn.Module):
    def __init__(self):
        super(BinaryClassificationModel, self).__init__()
        self.fc = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.fc(x)
        x = self.sigmoid(x)
        return x

# Create an instance of the model
model = BinaryClassificationModel()

# Define the loss function and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

# Training loop
epochs = 5
for epoch in range(epochs):
    for x, y in data_loader:
        # Forward pass
        outputs = model(x)
        loss = criterion(outputs.squeeze(), y.float())

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

# Evaluate the model
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    for x, y in data_loader:
        outputs = model(x)
        predicted = (outputs.squeeze() >= 0.5).float()
        total += y.size(0)
        correct += (predicted == y).sum().item()

    accuracy = correct / total
    print(f"Test Accuracy: {accuracy:.4f}")

# Make predictions
model.eval()
with torch.no_grad():
    for x, y in data_loader:
        outputs = model(x)
        predicted = (outputs.squeeze() >= 0.5).float()
        for i in range(len(x)):
            print(f"Input: {x[i]}, True Label: {y[i]}, Predicted Label: {predicted[i]}")

x: tensor([[-0.1343,  1.6545],
        [ 0.9954, -0.1135],
        [ 0.2200,  1.2703],
        [ 0.5642,  0.6503],
        [-1.1904,  0.1859],
        [ 1.0730,  1.2403],
        [-0.0277, -0.5709],
        [ 0.7996, -0.7771],
        [-0.3263, -0.6544],
        [ 0.3505, -0.2499],
        [ 0.6206,  0.7602],
        [-1.6273,  1.4514],
        [ 0.1713,  0.6839],
        [ 0.6510,  0.1482],
        [ 0.6953, -1.5348],
        [ 0.6083,  0.3015],
        [ 0.2228,  1.3627],
        [ 0.2752, -0.3148],
        [ 0.8729, -1.0568],
        [-1.1864,  2.0655],
        [-0.2923,  0.5638],
        [-0.0184, -0.4903],
        [-0.0834, -0.4628],
        [-0.0669, -0.0407],
        [ 0.1234, -0.4695],
        [ 2.1706, -0.0398],
        [-0.0431, -1.0719],
        [-0.8824, -0.8317],
        [-1.2637,  0.2424],
        [ 0.9894, -2.1242],
        [ 0.6523, -0.5042],
        [ 1.2369,  0.8872]]), <class 'torch.Tensor'>, y: tensor([1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 

In [6]:
import torch
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)

for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [7]:
import torch
from torch.utils.data import TensorDataset

torch.manual_seed(1)
t_x = torch.rand([4, 3], dtype=torch.float32)
t_y = torch.arange(4)

joint_dataset = TensorDataset(t_x, t_y)

for data in joint_dataset:
    print(data)

(tensor([0.7576, 0.2793, 0.4031]), tensor(0))
(tensor([0.7347, 0.0293, 0.7999]), tensor(1))
(tensor([0.3971, 0.7544, 0.5695]), tensor(2))
(tensor([0.4388, 0.6387, 0.5247]), tensor(3))
