In [1]:
# import
import torch
import numpy as np

In [3]:
# initialize a tensor from a Python List
data = [
        [0, 1], 
        [2, 3],
        [4, 5]
       ]
tensor = torch.tensor(data)
tensor

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [4]:
# init float
tensor_float = torch.tensor(data, dtype=torch.float)
tensor_float

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [5]:
# init bool
tensor_bool = torch.tensor(data, dtype=torch.bool)
tensor_bool

tensor([[False,  True],
        [ True,  True],
        [ True,  True]])

In [6]:
# init from tensor
x = torch.tensor([[1., 2.], [3., 4.]])
x
# tensor([[1., 2.],
#         [3., 4.]])
# initialize a tensor of 0s
x_zeros = torch.zeros_like(x)
x_zeros
# tensor([[0., 0.],
#         [0., 0.]])

tensor([[0., 0.],
        [0., 0.]])

In [8]:
shape = (4, 2, 2)
x_zeros = torch.zeros(shape) # x_zeros = torch.zeros(4, 3, 2) is an alternative
x_zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [9]:
# initialize a 5x2 tensor, with 5 rows and 2 columns
x = torch.arange(10).reshape(5, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [10]:
# initialize a 5x2 tensor, with 5 rows and 2 columns
x = torch.arange(10).view(5, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [11]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [14]:
# matrix multiplication
tensor = torch.tensor([1, 2, 3])

# Element-wise matrix multiplication
tensor * tensor
# tensor([1, 4, 9])

tensor([1, 4, 9])

In [15]:
# matrix multiplication
torch.matmul(tensor, tensor)
# tensor(14)

tensor(14)

In [17]:
# transpose
# shapes need to be in the right way  
tensor_1 = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_1.shape)

tensor_2 = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
print(tensor_2.shape)

#torch.matmul(tensor_1, tensor_2)
# error

# tensor_2 is transposed
result = torch.matmul(tensor_1, tensor_2.T)
print(result.shape)
print(result)

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([3, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [18]:
# batch matrix multiplication
a = torch.tensor(np.arange(1, 13, dtype=np.int32)).view(2, 2, 3)
b = torch.tensor(np.arange(13, 25, dtype=np.int32)).view(2, 3, 2)

c = torch.matmul(a, b)
print(c.shape)
print(c)

torch.Size([2, 2, 2])
tensor([[[ 94, 100],
         [229, 244]],

        [[508, 532],
         [697, 730]]], dtype=torch.int32)


In [19]:
# pass the tensor through a dense layer
# define a dense layer
tensor = torch.tensor([[1, 2],
                       [3, 4],
                       [5, 6]], dtype=torch.float32)
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value
output = linear(tensor)
print(f"Input shape: {tensor.shape}\n")
# Input shape: torch.Size([3, 2])
print(f"Output shape: {output.shape}")
# Output shape: torch.Size([3, 6])

Input shape: torch.Size([3, 2])

Output shape: torch.Size([3, 6])


In [20]:
# reshape
x = torch.arange(1., 8.)
x.shape
# torch.Size([7])
x_reshaped = x.reshape(1, 7)
x_reshaped.shape
# torch.Size([1, 7])

torch.Size([1, 7])

In [21]:
# stack tensors on top of each other over the rows
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [25]:
# stack tensors on top of each other over the rows
x = torch.arange(1., 8.)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [24]:
# concat
x = torch.arange(1., 8.)
x_cat0 = torch.cat([x, x, x], dim=0)
x_cat0

tensor([1., 2., 3., 4., 5., 6., 7., 1., 2., 3., 4., 5., 6., 7., 1., 2., 3., 4.,
        5., 6., 7.])

In [26]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [27]:
x[0] # Equivalent to x[0, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
x[:, 0]

tensor([[1, 2, 3]])

In [29]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [30]:
x[0, 0, 0], x[0, 0, 0].item()

(tensor(1), 1)

In [31]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [32]:
# back to numpy
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))