In [1]:
# imports
import tensorflow as tf
import numpy as np

In [4]:
# initialize a tensor from a Python List
data = [
    [0, 1],
    [2, 3],
    [4, 5]
]
tensor = tf.constant(data, dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)>

In [5]:
tensor_float = tf.constant(data, dtype=tf.float32)
tensor_float

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 1.],
       [2., 3.],
       [4., 5.]], dtype=float32)>

In [6]:
x = tf.constant([[1., 2.], [3., 4.]])
x
x_zeros = tf.zeros_like(x)
x_zeros

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
shape = (4, 2, 2)
x_zeros = tf.zeros(shape)
x_zeros

<tf.Tensor: shape=(4, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]], dtype=float32)>

In [8]:
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [9]:
# add
tensor = tf.constant([1, 2, 3])
tensor + 10

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12, 13], dtype=int32)>

In [11]:
# transpose
tensor_1 = tf.constant([[1, 2],
                        [3, 4],
                        [5, 6]], dtype=tf.float32)

tensor_2 = tf.constant([[7, 10],
                        [8, 11], 
                        [9, 12]], dtype=tf.float32)

# tensor_2 is transposed
#tf.linalg.matmul(tensor_1, tf.transpose(tensor_2))

# batch matrix multiplication
a = tf.constant(np.arange(1, 13, dtype=np.int32).reshape(2, 2, 3))
b = tf.constant(np.arange(13, 25, dtype=np.int32).reshape(2, 3, 2))

c = tf.matmul(a, b)
c

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]], dtype=int32)>

In [12]:
# pass the tensor through a layer
tensor = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]], dtype=tf.float32)
# define a dense layer
linear = tf.keras.layers.Dense(units=6, input_shape=(2,))
output = linear(tensor)
print(f"Input shape: {tensor.shape}\n")
# Input shape: (3, 2)
print(f"Output shape: {output.shape}")

Input shape: (3, 2)

Output shape: (3, 6)


In [13]:
tensor.dtype
# <dtype: 'float32'>
tensor_float16 = tf.cast(tensor, tf.float16)
tensor_float16, tensor_float16.dtype

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=float16)>,
 tf.float16)

In [14]:
x = tf.range(1., 8.)
x.shape
# (7,)
x_reshaped = tf.reshape(x, (1, 7))
x_reshaped.shape
# (1, 7)

TensorShape([1, 7])

In [15]:
# stack tensors on top of each other over the rows
x_stacked = tf.stack([x, x, x, x], axis=0)
x_stacked

<tf.Tensor: shape=(4, 7), dtype=float32, numpy=
array([[1., 2., 3., 4., 5., 6., 7.],
       [1., 2., 3., 4., 5., 6., 7.],
       [1., 2., 3., 4., 5., 6., 7.],
       [1., 2., 3., 4., 5., 6., 7.]], dtype=float32)>

In [16]:
x_stacked = tf.stack([x, x, x, x], axis=1)
x_stacked

<tf.Tensor: shape=(7, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]], dtype=float32)>

In [18]:
x = tf.range(1., 8.)
x_cat0 = tf.concat([x, x, x], axis=0)
x_cat0

<tf.Tensor: shape=(21,), dtype=float32, numpy=
array([1., 2., 3., 4., 5., 6., 7., 1., 2., 3., 4., 5., 6., 7., 1., 2., 3.,
       4., 5., 6., 7.], dtype=float32)>

In [19]:
# Indexing
# get all values of 0th dimension and the 0 index of 1st dimension
x = tf.constant(list(range(1, 10)), shape=(1, 3, 3))
x, x.shape

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=int32)>,
 TensorShape([1, 3, 3]))

In [20]:
x[0] # Equivalent to x[0, :]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [21]:
x[:, 0]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [22]:
x[:, :, 1]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 5, 8]], dtype=int32)>

In [23]:
# get scalar
scalar = x[0, 0, 0].numpy()
scalar

1

In [24]:
array = np.arange(1.0, 8.0)
tensor = tf.convert_to_tensor(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 <tf.Tensor: shape=(7,), dtype=float64, numpy=array([1., 2., 3., 4., 5., 6., 7.])>)

In [25]:
tensor = tf.constant(np.arange(1, 13))
tensor

<tf.Tensor: shape=(12,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])>

In [26]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(<tf.Tensor: shape=(12,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])>,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))